### ISSUE TITLE
Would like ability to use scope with param

### ISSUE THREAD

**Issue by michaelminter** [FortySource/forty_facets#10]
like: `scope :model_scope, name: 'GeneralScope', attr: :input`

**Comment by axelerator** [comment]
Well I'm not sure if this is what you're looking for since your question is not really elaborate ;-) . But I added an example to the demo app

https://github.com/fortytools/forty_facets_demo/commit/e9c784e27c762b825a536ac716c6614389eb6d80

hth

**Comment by michaelminter** [comment]
Would like the ability to use an argument with `scope`.

So model looks like: `scope :cars, ->(type) { where('auto = ?', type') }

Search class like: `scope :cars`. 

And `scope` accepts argument if required.

**Comment by antoineherzog** [comment]
@axelerator 
me too,
i wouldl like to this scope with a parameter in the model. Any help?

scope :with_campaign_id, ->(campaign_id) { where(campaign_id: campaign_id) }

**Comment by antoineherzog** [comment]
@axelerator any help? :) 👍

**Comment by axelerator** [comment]
But where is the campaign_id value supposed to come from?

**Comment by antoineherzog** [comment]
@axelerator 

in your readme you have

scope :classics   # only return movies which are in the scope 'classics'

i would like to be able to do:

scope :with_campaign_id,    # only return campaigns with a specific ID 

@search = CompanySearch.new(params) #.filter(:with_campaign_id).add(params[:campaign_id])

**Comment by antoineherzog** [comment]
@axelerator do you see what i mean?

**Comment by axelerator** [comment]
And why don't you just use a facet then? 

```
facet :campain_id
or
facet :campain
```

**Comment by antoineherzog** [comment]
@axelerator because even if i use face for campaign, others facets count will display wrong Total count. doesnt make sense ?

lets give an example

I have 2 campaigns. In campaign A, i have 1 company founded in the year 1930 and 1 company founded in 1949. In campaign B, i have only one company founded in 1949.

founded_year facet will display
1930 (2)
1949 (1)

With a Scope campaign A, I would like the plugin display founded_year:

1930 (1)

does that make sense @axelerator ?

**Comment by axelerator** [comment]
If you have a facet for **campaign** and **year**, with the data you give, you should get the facets

```
Campaign:
A (2)
B (1)

Year-Facet
1930 (1)
1949 (2)
```

Once you Filter on **campaign: A**  the number of 1949 will decrease since the company with campaign B founden in 1949 is not anymore in the result.

Compare i.e. http://forty-facets-demo.herokuapp.com/
When you filter a year the values for Genres will decrease

**Comment by antoineherzog** [comment]
@axelerator wonderful. thank you so much!
